FROM alpine
RUN apk update --no-cache
RUN apk add --no-cache \
    musl \
    build-base \
    python3 \
    python3-dev \
    bash \
    linux-headers \
    libffi-dev \
    py-pip
RUN pip3 install --no-cache-dir --upgrade pip 
RUN pip3 install flask
RUN pip3 install uwsgi
RUN pip3 install flask-pymongo
RUN pip3 install flask-bcrypt
RUN pip3 install PyJWT
RUN ln -sf /usr/bin/python3 /usr/bin/python && \
    ln -sf /usr/bin/pip3 /usr/bin/pip

EXPOSE 5000

ENV FLASK_APP=app.py
ENV FLASK_DEBUG=1
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY . .
WORKDIR /app
ENTRYPOINT [ "uwsgi" ]
CMD [ "--ini", "/app/app.ini" ]
